build:
  image: fedora:32
  script:
    - dnf group install -y 'Development Tools'
    - dnf install -y hdf5-devel gsl-devel flex bison
    - dnf install -y gtk3-devel cairo-devel pango-devel gdk-pixbuf2-devel fftw-devel ncurses-devel libpng-devel libtiff-devel
    - dnf install -y cmake
    - mkdir build && cd build && cmake .. && make
